from yacs.config import CfgNode as CN

ACTIVELEARNING = CN()
ACTIVELEARNING.BUDGET_AVG = 0
ACTIVELEARNING.BUDGET_ALL = 0
ACTIVELEARNING.PERCENT = 'u'
ACTIVELEARNING.UPDATE_EPOCHS = []
ACTIVELEARNING.START_EPOCH = 0

